Jessica_Rules/Models/ErrorViewModel.cs
using System;

namespace Jessica_Rules.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Jessica_Rules/Controllers/AngelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal;

namespace Jessica_Rules.Controllers
{
    public class AngelsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(FormPost form)
        {
            
            //
            return RedirectToAction("Edit", form);
        }

        public IActionResult Edit(FormPost form)
        {
            ViewData["Name"] = form.Name;
            ViewData["Email"] = form.Email;
            ViewData["Subject"] = form.Subject;
            ViewData["Body"] = form.Body;

            return View();
        }
    }

    public class FormPost
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
    }
}

Jessica_Rules/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Jessica_Rules.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }

        // GET: Default/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Default/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Default/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Default/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Default/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Default/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Default/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Jessica_Rules/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Jessica_Rules.Models;

namespace Jessica_Rules.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Jessica_Rules/Views/Angels/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_Layout_Music.cshtml";
}


<div id="Content">
    <div class="content_wrapper clearfix">
        <div class="sections_group">
            <div class="entry-content">
                <div class="section mcb-section" style="padding-top:120px; padding-bottom:80px;" data-parallax="3d">
                    <img class="mfn-parallax" src="~/Music/images/home_music_sectionbg1.png" alt="parallax background" />
                    <div class="section_wrapper mcb-section-inner">
                        <div class="wrap mcb-wrap one-second  valign-top clearfix" style="padding:0 2% 0 0">
                            <div class="mcb-wrap-inner">
                                <div class="column mcb-column one column_image ">
                                    <div class="image_frame image_item no_link scale-with-grid aligncenter no_border">
                                        <div class="image_wrapper">
                                            <img class="scale-with-grid" src="~/Music/images/home_music_contact1.png" alt="home_music_contact1" width="481" height="526" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="wrap mcb-wrap one-second  valign-top clearfix" style="padding:0 0 0 2%">
                            <div class="mcb-wrap-inner">
                                <div class="column mcb-column one column_column  column-margin-20px">
                                    <div class="column_attr">
                                        <h3>Vestibulum tincidunt ornare</h3>
                                        <p class="big">
                                            Phasellus id lacus dapibus, tristique odio in, faucibus velit mauris mattis tincidunt. Sed eget erat arcu. Sed viverra turpis duis. Proin diam orci, ultricies ac ipsum eget, sodales hendrerit sem. Duis vel faucibus urna. Curabitur iaculis ornare tincidunt.
                                        </p>
                                    </div>
                                </div>
                                <div class="column mcb-column one column_column  ">
                                    <div class="column_attr">
                                        <div id="contactWrapper">
                                            <form id="contactform" method="post" asp-action="Contact" asp-controller="Angels">
                                                <div class="column one-second">
                                                    <input placeholder="Your name" type="text" name="Name" id="name" size="40" aria-required="true" aria-invalid="false" />
                                                </div>
                                                <div class="column one-second">
                                                    <input placeholder="Your e-mail" type="email" name="Email" id="email" size="40" aria-required="true" aria-invalid="false" />
                                                </div>
                                                <div class="column one">
                                                    <input placeholder="Subject" type="text" name="Subject" id="subject" size="40" aria-invalid="false" />
                                                </div>
                                                <div class="column one">
                                                    <textarea placeholder="Message" name="Body" id="body" style="width:100%;" rows="10" aria-invalid="false"></textarea>
                                                </div>
                                                <div class="column one">
                                                    <input type="submit" value="Send A Message" id="submit" onClick="return check_values();">
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="wrap mcb-wrap one  valign-top clearfix">
                            <div class="mcb-wrap-inner">
                                <div class="column mcb-column one column_divider ">
                                    <hr class="no_line" style="margin: 0 auto 30px;" />
                                </div>
                            </div>
                        </div>
                        <div class="wrap mcb-wrap one-second  valign-top clearfix" style="padding:0 2% 0 0">
                            <div class="mcb-wrap-inner">
                                <div class="column mcb-column one column_image ">
                                    <div class="image_frame image_item no_link scale-with-grid no_border">
                                        <div class="image_wrapper">
                                            <img class="scale-with-grid" src="~/Music/images/home_music_contact2.png" alt="home_music_contact2" width="132" height="100" />
                                        </div>
                                    </div>
                                </div>
                                <div class="column mcb-column one column_column  column-margin-20px">
                                    <div class="column_attr">
                                        <h4>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat proident.</h4>
                                        <hr class="no_line" style="margin: 0 auto 30px;" />
                                        <p style="font-size: 36px; line-height: 36px;">
                                            <a href="#"><i class="icon-facebook-circled"></i></a><a href="#"><i class="icon-gplus-circled"></i></a><a href="#"><i class="icon-twitter-circled"></i></a><a href="#"><i class="icon-pinterest-circled"></i></a><a href="#"><i class="icon-linkedin-circled"></i></a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="wrap mcb-wrap one-second  valign-top clearfix" style="padding:0 0 0 2%">
                            <div class="mcb-wrap-inner">
                                <div class="column mcb-column one column_column  column-margin-20px">
                                    <div class="column_attr">
                                        <h3>Curabitur iaculis</h3>
                                        <p class="big">
                                            Nam euismod ipsum eu neque bibendum, non mollis risus viverra. Suspendisse tempor massa justo, a feugiat enim iaculis consectetur. Aliquam rhoncus.
                                        </p>
                                    </div>
                                </div>
                                <div class="column mcb-column one-second column_column  ">
                                    <div class="column_attr" style=" padding:0 5% 0 0;">
                                        <h6>Sed imperdiet leo nec imperdiet elementum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos auctor.</h6>
                                        <p>
                                            In eu pulvinar sem. Fusce sed venenatis ligula. Mauris pharetra pulvinar hendrerit. Suspendisse condimentum velit odio, at fermentum augue lacinia sed.
                                        </p>
                                    </div>
                                </div>
                                <div class="column mcb-column one-second column_column  ">
                                    <div class="column_attr" style=" padding:0 5% 0 0;">
                                        <h6>Donec sed ex eu justo consectetur euismod at sit amet nisl. Nam cursus dignissim posuere. Ut vitae tellus viverra, molestie magna sed, commodo dui orci aliquam.</h6>
                                        <p>
                                            Ut nisi augue, accumsan id viverra nec, hendrerit at nulla. Nunc vel imperdiet turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="section the_content no_content">
                    <div class="section_wrapper">
                        <div class="the_content_wrapper"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Jessica_Rules/Views/Angels/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout_Music.cshtml";
}

<h1>@ViewData["Name"]</h1>
<h1>@ViewData["Email"]</h1>
<h1>@ViewData["Subject"]</h1>
<h1>@ViewData["Body"]</h1>

Jessica_Rules/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Jessica. This is my first app.</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Jessica_Rules/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Jessica_Rules</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Jessica_Rules</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Jessica_Rules - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Jessica_Rules/Views/Shared/_Layout_Music.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie10 lt-ie9 lt-ie8 lt-ie7 "> <![endif]-->
<!--[if IE 7]><html class="no-js lt-ie10 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]><html class="no-js lt-ie10 lt-ie9"> <![endif]-->
<!--[if IE 9]><html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <title>Be</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Mobile Specific Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- Favicons -->
    <link rel="shortcut icon" href="content/music/images/favicon.ico">
    <!-- FONTS -->
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:100,300,400,400italic,700'>
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Patua+One:100,300,400,400italic,700'>
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Lato:300,400,400italic,700,700italic'>
    <!-- CSS -->
    <link rel='stylesheet' href='~/Music/css/global.css'>
    <link rel='stylesheet' href='~/Music/css/structure.css'>
    <link rel='stylesheet' href='~/Music/css/music.css'>
    <link rel='stylesheet' href='~/Music/css/custom.css'>
    <!-- Revolution Slider -->
    <link rel="stylesheet" href="plugins/rs-plugin/css/settings.css">
</head>
<body class="template-slider color-custom style-default layout-full-width nice-scroll-on mobile-tb-hide button-flat if-zoom no-content-padding header-transparent header-fw minimalist-header-no sticky-header sticky-white ab-hide subheader-both-center menuo-right menuo-no-borders footer-copy-center">
    <div id="Wrapper">
        <div id="Header_wrapper">
            <header id="Header">
                <div class="header_placeholder"></div>
                <div id="Top_bar">
                    <div class="container">
                        <div class="column one">
                            <div class="top_bar_left clearfix">
                                <div class="logo">
                                    <a id="logo" href="index-music.html" title="BeMusic - BeTheme">
                                        <img class="logo-main scale-with-grid" src="content/music/images/music.png" alt="music" /><img class="logo-sticky scale-with-grid" src="content/music/images/music.png" alt="music" /><img class="logo-mobile scale-with-grid" src="content/music/images/music.png" alt="music" />
                                    </a>
                                </div>
                                <div class="menu_wrapper">
                                    <nav id="menu" class="menu-main-menu-container">
                                        <ul id="menu-main-menu" class="menu">
                                            <li class="current_page_item">
                                                <a href="index-music.html"><span>Home</span></a>
                                            </li>
                                            <li>
                                                <a href="https://www.google.com"><span>About us</span></a>
                                            </li>
                                            <li>
                                                <a href="content/music/the-studio.html"><span>The studio</span></a>
                                            </li>
                                            <li>
                                                <a href="content/music/our-tracks.html"><span>Our tracks</span></a>
                                            </li>
                                            <li>
                                                <a href="content/music/contact.html"><span>Contact Us</span></a>
                                            </li>
                                            
                                        </ul>
                                    </nav><a class="responsive-menu-toggle" href="#"><i class="icon-menu"></i></a>
                                </div>
                                <div class="secondary_menu_wrapper"></div>
                                <div class="banner_wrapper"></div>
                                <div class="search_wrapper">
                                    <form method="get" id="searchform" action="#">
                                        <i class="icon_search icon-search"></i><a href="#" class="icon_close"><i class="icon-cancel"></i></a>
                                        <input type="text" class="field" name="s" id="s" placeholder="Enter your search" />
                                        <input type="submit" class="submit" value="" style="display:none;" />
                                    </form>
                                </div>
                            </div>
                            <div class="top_bar_right">
                                <div class="top_bar_right_wrapper">
                                    <a href="http://bit.ly/1M6lijQ" class="button button_theme button_js action_button " target="_blank"><span class="button_label">Buy now</span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="mfn-main-slider" id="mfn-rev-slider">
                    <div id="rev_slider_1_2_wrapper" class="rev_slider_wrapper fullwidthbanner-container" style="margin:0px auto;background-color:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">
                        <div id="rev_slider_1_2" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.2.1">
                            <ul>
                                <li data-index="rs-1" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                                    <img src="content/music/images/home_music_slider.jpg" alt="" title="home_music_slider" width="1920" height="1100" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="7" class="rev-slidebg" data-no-retina>
                                    <div class="tp-caption   tp-resizeme rs-parallaxlevel-2" id="slide-1-layer-2" data-x="center" data-hoffset="" data-y="center" data-voffset="" data-width="['none','none','none','none']" data-height="['none','none','none','none']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:1000;e:Power2.easeOut;" data-transform_out="opacity:0;s:300;s:300;" data-start="500" data-responsive_offset="on" style="z-index: 5;"><img src="content/music/images/home_music_slider_slogan.png" alt="" width="605" height="161" data-ww="605px" data-hh="161px" data-no-retina> </div>
                                </li>
                            </ul>
                            <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>
                        </div>
                    </div>
                </div>
            </header>
        </div>
        
        @RenderBody();

        <footer id="Footer" class="clearfix">
            <div class="widgets_wrapper" style="padding:60px 0 45px;">
                <div class="container">
                    <div class="column one">
                        <aside class="widget widget_text">
                            <div class="textwidget">
                                <div style="text-align: center; margin: 0 10%;">
                                    <div class="image_frame image_item no_link scale-with-grid alignnone no_border">
                                        <div class="image_wrapper"><img class="scale-with-grid" src="content/music/images/home_music_list_footer_logo.png" alt="home_music_list_footer_logo" width="66" height="50" /> </div>
                                    </div>
                                    <hr class="no_line" style="margin: 0 auto 20px;" />
                                    <p>
                                        Pellentesque rhoncus mollis lorem cursus dignissim. Cras scelerisque ex et placerat condimentum. Duis hendrerit justo vitae arcu finibus lobortis. Suspendisse sed augue a nibh condimentum porttitor. Phasellus luctus, ligula sed fringilla auctor, ligula massa volutpat lacus, eget gravida justo ante nec metus massa nunc id eleifend lacus.
                                    </p>
                                </div>
                            </div>
                        </aside>
                    </div>
                </div>
            </div>
            <div class="footer_copy">
                <div class="container">
                    <div class="column one">
                        <div class="copyright">
                            &copy; 2017 BeMusic - BeTheme. Muffin group - HTML by <a target="_blank" rel="nofollow" href="http://bit.ly/1M6lijQ">BeantownThemes</a>
                        </div>
                        <ul class="social"></ul>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <!-- JS -->
    <script src="js/jquery-2.1.4.min.js"></script>
    <script src="js/mfn.menu.js"></script>
    <script src="js/jquery.plugins.js"></script>
    <script src="js/jquery.jplayer.min.js"></script>
    <script src="js/animations/animations.js"></script>
    <script src="js/translate3d.js"></script>
    <script src="js/scripts.js"></script>
    <script src="plugins/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
    <script src="plugins/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
    <script src="plugins/rs-plugin/js/extensions/revolution.extension.video.min.js"></script>
    <script src="plugins/rs-plugin/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script src="plugins/rs-plugin/js/extensions/revolution.extension.actions.min.js"></script>
    <script src="plugins/rs-plugin/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script src="plugins/rs-plugin/js/extensions/revolution.extension.kenburn.min.js"></script>
    <script src="plugins/rs-plugin/js/extensions/revolution.extension.navigation.min.js"></script>
    <script src="plugins/rs-plugin/js/extensions/revolution.extension.migration.min.js"></script>
    <script src="plugins/rs-plugin/js/extensions/revolution.extension.parallax.min.js"></script>
    <script>
var tpj = jQuery;
        var revapi1;
        tpj(document).ready(function() {
            if (tpj("#rev_slider_1_2").revolution == undefined) {
                revslider_showDoubleJqueryError("#rev_slider_1_2");
            } else {
                revapi1 = tpj("#rev_slider_1_2").show().revolution({
                    sliderType: "hero",
                    sliderLayout: "auto",
                    dottedOverlay: "none",
                    delay: 9000,
                    navigation: {},
                    visibilityLevels: [1240, 1024, 778, 480],
                    gridwidth: 1240,
                    gridheight: 1100,
                    lazyType: "none",
                    parallax: {
                        type: "scroll",
                        origo: "enterpoint",
                        speed: 400,
                        levels: [5, 10, 15, 20, 25, 30, 35, 40, 45, 46, 47, 48, 49, 50, 51, 55],
                        type: "scroll",
                    },
                    shadow: 0,
                    spinner: "spinner2",
                    autoHeight: "off",
                    disableProgressBar: "on",
                    hideThumbsOnMobile: "off",
                    hideSliderAtLimit: 0,
                    hideCaptionAtLimit: 0,
                    hideAllCaptionAtLilmit: 0,
                    debugMode: false,
                    fallbacks: {
                        simplifyAll: "off",
                        disableFocusListener: false,
                    }
                });
            }
        });</script>
    <script id="mfn-dnmc-retina-js">
jQuery(window).load(function() {
            var retina = window.devicePixelRatio > 1 ? true : false;
            if (retina) {
                var retinaEl = jQuery("#logo img.logo-main");
                var retinaLogoW = retinaEl.width();
                var retinaLogoH = retinaEl.height();
                retinaEl.attr("src", "content/music/images/retina-music.png").width(retinaLogoW).height(retinaLogoH);
                var stickyEl = jQuery("#logo img.logo-sticky");
                var stickyLogoW = stickyEl.width();
                var stickyLogoH = stickyEl.height();
                stickyEl.attr("src", "content/music/images/retina-music.png").width(stickyLogoW).height(stickyLogoH);
                var mobileEl = jQuery("#logo img.logo-mobile");
                var mobileLogoW = mobileEl.width();
                var mobileLogoH = mobileEl.height();
                mobileEl.attr("src", "content/music/images/retina-music.png").width(mobileLogoW).height(mobileLogoH);
            }
        });</script>
</body>
</html>